###
post  http://localhost:3008/add
Content-Type: application/json

{
    "userName":"bhagyalaxmi",
    "email":"lbhagya818@gmail.com",
    "password":"bhagya2023",
    "confirmPassword":"bhagya2023",
    "id":"1"
}



###
post http://localhost:3008/login
Content-Type: application/json

{
    "email":"lbhagya818@gmail.com",
    "password":"bhagya2023"

}



###
get http://localhost:3008/userName
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxiaGFneWE4MThAZ21haWwuY29tIiwiaWF0IjoxNjc4NTUxMTMzLCJleHAiOjE2ODIxNTExMzN9.3KEk1arBX1B7MnVV_z9FWmqrZApPRlv9lHuu6HeWp4U